### ISSUE TITLE
Bundling Useful Gems into the Omnibus?

### ISSUE THREAD

**Issue by solarkennedy** [sensu/sensu-build#96]
Often on the mailing list people have questions regarding installing rubygems in order to support some of the popular community plugins.

If gems the aws-sdk and sensu-cli were included in the omnibus, this would greatly increase the usability of the community plugins, *and* they could set their #! to be the omnibus interpreter and be sure it could work.

Also, this would greatly reduce my workload in supporting different gems across lots of distros, because it would be taken care of upstream, at the cost of increased builds and package sizes.

Do you think this is an acceptable tradeoff? Would you accept a PR if I increased the gemfile and documented the supported gems that the omnibus package comes with?

cc @bobtfish

**Comment by calebhailey** [comment]
@solarkennedy @bobtfish hi there! :wave: 

Sorry for the radio silence on this. A lot has changed since this issue was created, including major changes in how the Sensu Plugins are maintained (and shipped as individual Ruby gems) + the change to using `EMBEDDED_RUBY=true` by default since 0.20 + the release of [a new `sensu-install` utility for installing Sensu plugins][1]. I wonder if we can close this? :smile: 

/cc @portertech 

[1]: https://sensuapp.org/docs/latest/plugins#sensu-install-example

**Comment by solarkennedy** [comment]
Fancy. 

Yes, with the new way that the plugins are installed (as gems) this isn't *as* relevant.

If we (at yelp) want to do this our ourselves to make it easier to distribute then we can do our own repackaging.
